sequenceDiagram
    Note left of SSH: 3. Trigger Alarm
    SSH -->> Boutton Alarm: COAP GET alarm
    Note left of Boutton Alarm: A user has activated the alarm
    Boutton Alarm ->> Central server: COAP GET alarm
