sequenceDiagram
    Note left of SSH: 1. Server can show Diagram
    SSH -->> Server: Set Threeshold
    Server ->> CapteurCOAP: GET Temp
    Server ->> Capteur HTTP: GET Pressure
    Server ->> Acuator: Stop motor
    Note left of SSH: 2. Set threeshold
    Server ->> Autonomous Captor: Send Threeshold
    Note right of Autonomous Captor: Get the gyro and stop it if needed (> threeshold)
    Autonomous Captor ->> Server: Stopped the gyro
    Note left of SSH: 3. Trigger Alarm
    SSH -->> Boutton Alarm: Trigger ALARM
    Boutton Alarm ->> Server: ALERT
